// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "syntaxhl_logging.h"

 namespace syntaxhl {
#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(Log, "org.kde.syntaxhl", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(Log, "org.kde.syntaxhl")
#endif
} 
